### ISSUE TITLE
Unable to delete artifacts uploaded by `actions/upload-artifact@v4`

### ISSUE THREAD

**Issue by muzimuzhi** [GeekyEggo/delete-artifact#14]
An example workflow: https://github.com/muzimuzhi/hello-github-actions/actions/runs/7256001370

More comparisons can be found in https://github.com/muzimuzhi/hello-github-actions/pull/24. It seems changes more than a naive package upgrading are needed (I'm not a front-end developer). Also the `listArtifacts()` function from [`@actions/artifact`](https://github.com/actions/toolkit/blob/main/packages/artifact) might be helpful.

Several breaking changes were introduced in `actions/upload-artifact@v4`, see
- GitHub Blog https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
- `@actions/artifact` https://github.com/actions/toolkit/tree/main/packages/artifact

**Comment by GeekyEggo** [comment]
Hi @muzimuzhi, thanks for bringing this to my attention.

I've prepared a pull request (#17) that introduces support for `actions/upload-artifact@v4` by utilizing the GitHub REST API; as a result of this change is the requirement of a PAT with read and write access when running the action.

**Comment by muzimuzhi** [comment]
Thanks! I confirm with https://github.com/GeekyEggo/delete-artifact/pull/17 now `GeekyEggo/delete-artifact@main` [works as expected](https://github.com/muzimuzhi/hello-github-actions/actions/runs/7316485211/job/19931151681). 🎉

Looking forward to a v4.0.0 release.

BTW then two `example.yml` may be needed, one for v2 and one for v4.

**Comment by GeekyEggo** [comment]
`geekyeggo/delete-artifact@v4` has been tagged and released, and the examples have been updated. 🎉

If you experience any problems, please let me know. Happy holidays.

**Comment by rolfkoizumi** [comment]
I have just upgraded our upload/download actions from @v3 to @v4 - and also tried updating this action to @v4
Out of the box, we are getting this error:
<img width="550" alt="image" src="https://github.com/GeekyEggo/delete-artifact/assets/4116297/df6e0ee3-1855-4f42-9d41-87b9303bff0a">

Exactly the same setup with all actions@v3 worked. One thing though - the `actions/upload-artifact@v4` and `geekyeggo/delete-artifact@v4` are in two different subsequent jobs.

I have tried:
* using `geekyeggo/delete-artifact@4.1.0`
* using `geekyeggo/delete-artifact@4`
* no `token` parameter
* with parameter `token: ${{ github.token }}` (no extra PAT created, this should use the default github token)
* with parameter `token: ${{ secrets.GITHUB_TOKEN }}` (no extra PAT created, this should use the default github token)

I have then tried deleting the artifact inside the same job in a subsequent step instead of in the next job. This worked.

This is the upload-step in one job:
![image](https://github.com/GeekyEggo/delete-artifact/assets/4116297/4fcdfa5b-2e78-47ec-9f8a-598fc289d0c5)
And this is the delete-step in a subsequent job:
![image](https://github.com/GeekyEggo/delete-artifact/assets/4116297/57e1c6e3-0578-4195-b602-7f4302565cd0)
I have checked that the `name` is exactly the same in the upload and delete step.

I'd greatly appreciate any ideas to what I'm doing wrong.

**Comment by muzimuzhi** [comment]
@rolfboom Seems like related to workflow permissions, see a similar post https://github.com/orgs/community/discussions/60820.

BTW, better to raise a new issue.

**Comment by Bouni** [comment]
For me the solution was to add `actions: write`

```
deploy:
  name: "Deploy"
  runs-on: ubuntu-20.04
  permissions:
      actions: write
  steps:
     - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      # delete-artifact
      - name: Clean
        uses: geekyeggo/delete-artifact@v4
        with:
          name: github-pages
